######################## default configuration ####################
#baseURL = "http://localhost:1313/"
languageCode = "fr-FR"
title = "FRITAY VYBZ"
theme = "restaurant-hugo"
summaryLength = "10"
pagination.pagerSize = 6
