######################## default configuration ####################
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Restaurant Hugo"
theme = "restaurant-hugo"
summaryLength = "10"
pagination.pagerSize = 4
