# --------------------------
# English language
# --------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1

[fr]
languageName = "Fr"
languageCode = "fr-FR"
contentDir = "content"
weight = 1
