############################## navigation ###############################

[[main]]
name = "ACCUEIL"
URL = "about-us"
weight = 1

# [[main]]
# name = "À PROPOS"
# URL = "about-us"
# weight = 2

[[main]]
name = "MENU"
URL = "blog"
weight = 3

[[main]]
name = "PRIX"
URL = "price"
weight = 4

[[main]]
name = "CONTACT"
URL = "contact-us"
weight = 6

