baseURL = "http://localhost:1313/"
languageCode = "fr-FR"
title = "FRITAY VYBZ"
theme = "restaurant-hugo"
summaryLength = "10"

[pagination]
pagerSize = 4

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "<span>CONTACT</span>"
blogTitle = "<span>DISPONIBLE CETTE SEMAINE...</span>"
galleryTitle = "NOS <span>PLATS</span>"
socialTitle = "<span>SUIVEZ NOUS</span>"

############################ footer contact item
[[params.footer.contactItem]]
title = "Téléphone"
icon = "fa fa-phone"
content = "+509 3456-7890"
link = "tel:+50934567890"

[[params.footer.contactItem]]
title = "Adresse"
icon = "fa fa-map-marker"
content = "Delmas 31, Port-au-Prince, Haïti"
link = "https://maps.app.goo.gl/YourGoogleMapsLink"

[[params.footer.contactItem]]
title = "E-mail"
icon = "fa fa-envelope"
content = "contact@fritayvybz.ht"
link = "mailto:contact@fritayvybz.ht"

######################### footer gallery - Plats haïtiens
[[params.footer.gallery]]
image = "images/fritay-mix.png"

[[params.footer.gallery]]
image = "images/poulet-frit.png"

[[params.footer.gallery]]
image = "images/porc-frit.png"

[[params.footer.gallery]]
image = "images/pastels.png"

######################## Social Icon - Réseaux haïtiens
[[params.footer.socialLink]]
icon = "facebook"
link = "https://facebook.com/fritayvybz"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://instagram.com/fritayvybz"

[[params.footer.socialLink]]
icon = "youtube"
link = "https://youtube.com/@fritayvybz"

[[params.footer.socialLink]]
icon = "whatsapp"
link = "https://wa.me/50934567890"
